name: Auto Trigger Deploy

on:
  push:
    branches:
      - flutterflow

jobs:
  trigger:
    if: "!contains(github.event.head_commit.message, 'ci: auto deploy trigger')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          ref: flutterflow

      - name: Push vazio para triggar deploy
        run: |
          git config user.email "hpsrefri@gmail.com"
          git config user.name "HPS Deploy Bot"
          git commit --allow-empty -m "ci: auto deploy trigger"
          git push origin flutterflow
